### ISSUE TITLE
Network Value Chain

### ISSUE THREAD

**Issue by voiptecben** [Open-Telecoms-Data/open-fibre-data-standard#120]
In the "network value chain" page the concepts are well defines but it doesn't reflect that there can be more than one network provider. The definition of network provider talks of "The network provider" and the diagram does not show multiple network providers. Its now common to have multiple network providers in infra sharing contracts where multiple providers take multiple fibre strands. Normally there is only one physical infrastructure provider though, but this can be an SPV co owned by the network providers.

**Comment by lgs85** [comment]
Thanks @voiptecben and good spot. The [schema](https://open-fibre-data-standard.readthedocs.io/en/latest/reference/schema.html#) itself does allow for multiple network providers (by making network providers a property of a link or a node rather than a property of a network), and I agree that the primer needs to reflect this. We'll look to update for the Beta standard.

**Comment by lgs85** [comment]
@voiptecben I've put together a PR (#140) that looks to address this. You can preview the changes to the primer [here](https://open-fibre-data-standard.readthedocs.io/en/0.1-dev/primer/scopeandkeyconcepts.html). We just wanted to check that this addresses your concerns before closing this issue? Let us know if you have any questions.
