### ISSUE TITLE
Replace the $ref in publisher with the properties we desire from Organisation, e.g. name etc.

### ISSUE THREAD

**Issue by lgs85** [Open-Telecoms-Data/open-fibre-data-standard#190]
At present the `publisher` field is included at the network level in the schema, and contains a reference to the organisation definition. The organisation definition contains a `roles` field which refers to the `organisationRole` codelist, which doesn't contain anything about publishers. In the example data we don't include `roles` in the `publisher` object, but I don't think it's clear to users that this should be the approach (and I'm not sure it's the right one). Either some clarifying guidance, or moving `publisher` to `organisations` and adding an organisation reference are two possible approaches here.

**Comment by duncandewhurst** [comment]
I don't think we should make `publisher` an `organisationReference` since the publisher of a dataset doesn't fit the semantics of `organisations` (Information about the organisations involved in this network.).

Another option is to replace the `$ref` in `publisher` with the properties we desire from `Organisation`, e.g. `name` etc. In OCDS 1.2, `publisher` is an [`Identifier`](https://standard.open-contracting.org/staging/1.2-dev/en/schema/reference/#identifier).

**Comment by duncandewhurst** [comment]
Forgot to say, good spot :-)

**Comment by lgs85** [comment]
>Another option is to replace the `$ref` in `publisher` with the properties we desire from `Organisation`, e.g. `name` etc.

Yes, this is fine too
