### ISSUE TITLE
Make `roleDetails` a feature of nodes and spans

### ISSUE THREAD

**Issue by lgs85** [Open-Telecoms-Data/open-fibre-data-standard#202]
In the network-level `organisations`, it's possible to specify, for each organisation, their `roles` in the network as an array, and to provide further `roleDetails` as a free-text string. However, it is likely that the role details will differ substantially across spans and nodes, and this information is going to be important for understanding organisational structure in early stages of implementation, and for distinguishing between different spans following the same route (see #192). We should consider allowing publishers to specify  `roleDetails` at the node and span level until we have a better understanding of these organisational structures.

**Comment by duncandewhurst** [comment]
I think we'd want to make `.roleDetails` a property of `OrganisationReference` because:
* There can be different organisations associated with a span: `.physicalInfrastructureProvider`, `.networkProvider` and `.supplier`.
* Making details of an organisation's role a property of `Span` or `Node` doesn't really make sense ontologically.

We'd then need to think about the interaction between `OrganisationReference.roleDetails` and `Organisation.roleDetails`. I don't think we want a strict relationship, e.g. `Organisation.roleDetails` being the intersection of all the `OrganisationReference.roleDetails`. We might instead define `OrganisationReference.roleDetails` as:

> Further details about the organisation's role in this context. See also, `Organisation.role` and `Organisation.roleDetails`.

With an accompanying update to the definition of `Organisation.roleDetails`:

> Further details about the organisation’s roles in the network. See also, `OrganisationReference.roleDetails`.

The downside of this approach is that, unlike `.id` and `.name`, `.roleDetails` is not consistent between `OrganisationReference` and `Organisation`, which could be confusing for implementers.

I'm somewhat skeptical that implementers will actually populate this field as we didn't see any examples of this type of data in the supply-side research so I'm minded to think that we hold off on updating the schema. Instead, implementers can add `OrganisationReference.roleDetails` as an [additional field](https://open-fibre-data-standard.readthedocs.io/en/latest/guidance/publication.html#how-to-add-additional-fields) if the current schema isn't sufficient to represent their data. If we see the field used in more than one implementation, we can consider adding it to the standard.

**Comment by lgs85** [comment]
Thanks @duncandewhurst

>I'm somewhat skeptical that implementers will actually populate this field as we didn't see any examples of this type of data in the supply-side research so I'm minded to think that we hold off on updating the schema

I think this is likely, at least in part, because there hasn't been a good way to represent this information, and we don't want to perpetuate this issue. I've already been asked 'how should I represent [scenario x]' by potential implementers, and I think we need a good solution.

That said, I agree with this:

> The downside of this approach is that, unlike .id and .name, .roleDetails is not consistent between OrganisationReference and Organisation, which could be confusing for implementers.

As such I don't think that this is the solution to the issue of multiple roles on single spans/nodes, so closing this of a wider discussion in #192
